import Link from "next/link";

const useCases = [
  {product:"Medicine Loop",case:"Cross-setting medication change not fully propagated",include:"Adults with a clinically authorised medication stop, start, dose or formulation change originating in hospital or another participating service and requiring downstream action.",exclude:"Changes with unclear provenance, emergency situations outside the agreed workflow, or records that cannot be safely linked.",primary:"Time from authorised change to all required downstream reconciliations complete.",secondary:"Open discrepancies, obsolete repeats/supply/admin states prevented, workload per case, safety events and escalation burden."},
  {product:"WasteGuard",case:"Potential repeat supply not required this cycle",include:"Selected repeat medicines in agreed stable cohorts where dispensing history, timing, medication state and stock/use information are available.",exclude:"High-risk medicines or cohorts excluded by the clinical safety case, urgent supply, or cases where a delay could create unacceptable harm.",primary:"Verified supplies safely deferred or avoided after human review.",secondary:"False-positive rate, pharmacist/prescriber workload, patient experience, subsequent urgent supply, cost avoidance and safety."},
  {product:"Medicines Resource Intelligence",case:"Evidence-backed pathway alternative",include:"One or two high-volume or resource-intensive medicine pathways with an established evidence base and a locally plausible alternative.",exclude:"Pathways without agreed clinical eligibility criteria, insufficient baseline data or unresolved safety/governance requirements.",primary:"Observed local change in the pre-agreed resource measure after implementation.",secondary:"Pharmacy/nursing minutes, chair/bed capacity, consumables, unused doses, acquisition cost, patient impact, safety and actual capacity reuse."}
];

export default function PilotProtocolPage(){return <>
  <section className="page-head"><div className="shell"><div className="eyebrow">Pilot readiness pack · protocol</div><h1>A controlled medicines evaluation with explicit inclusion, ownership and stopping rules.</h1><p className="lede">The purpose is not to prove Sitora right. It is to determine whether the three workflows create safe, measurable and operationally worthwhile benefit in a real NHS setting.</p><div className="hero-actions"><Link className="button primary" href="/data-specification">Minimum data specification</Link><Link className="button secondary" href="/technical-implementation">Technical implementation</Link></div></div></section>

  <section className="section"><div className="shell metric-grid"><div className="metric"><span className="badge">Duration</span><strong>20 weeks</strong><h3>Mobilise to decision</h3><small>Includes baseline, shadow mode, controlled intervention and evaluation.</small></div><div className="metric"><span className="badge">Products</span><strong>3</strong><h3>Separate workstreams</h3><small>Each has its own denominator, intervention and outcome.</small></div><div className="metric"><span className="badge">Decision</span><strong>Pre-set</strong><h3>Scale / modify / stop</h3><small>Thresholds agreed before intervention begins.</small></div><div className="metric"><span className="badge">Safety</span><strong>Human</strong><h3>Professional control</h3><small>No autonomous prescribing or medication-state changes.</small></div></div></section>

  <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Three pilot use cases</div><h2>Each question has a defined population and endpoint.</h2></div></div><div className="opportunity-stack">{useCases.map((u)=><article className="card evidence-card" key={u.product}><div className="meta-row"><span className="badge">{u.product}</span><span>{u.case}</span></div><h2>{u.case}</h2><div className="two-col"><div><h3>Include</h3><p>{u.include}</p><h3>Exclude</h3><p>{u.exclude}</p></div><div><h3>Primary endpoint</h3><p>{u.primary}</p><h3>Secondary endpoints</h3><p>{u.secondary}</p></div></div></article>)}</div></div></section>

  <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Operating model</div><h2>Every signal has an owner and a clock.</h2></div></div><div className="process">{[["01","Detect","Sitora creates a signal or open medication-change event from agreed source data."],["02","Triage","Rules classify urgency, provenance, completeness and responsible service."],["03","Review","Named professional reviews the case when clinical judgement is required."],["04","Act","The responsible service reconciles, defers, implements or rejects the proposed action."],["05","Close","Outcome, workload, safety and benefit classification are recorded before the case closes."]].map(([n,t,b])=><div className="process-step" key={t}><span>{n}</span><h3>{t}</h3><p>{b}</p></div>)}</div></div></section>

  <section className="section"><div className="shell two-col"><div><div className="eyebrow">Service levels</div><h2>Suggested pilot response rules.</h2><ul className="list-clean"><li><strong>Urgent discrepancy:</strong> immediate routing into existing local clinical escalation, not a new Sitora-only process.</li><li><strong>Routine medication-change action:</strong> acknowledged within 1 working day, reconciled within a locally agreed window.</li><li><strong>WasteGuard review:</strong> resolved before the relevant dispensing event where operationally feasible.</li><li><strong>Resource opportunity:</strong> no live change until pathway owner and clinical governance approve the intervention.</li><li><strong>Unresolved ownership:</strong> escalated to the pilot clinical lead.</li></ul></div><div className="card"><span className="badge">Closure definition</span><h3 style={{marginTop:12}}>A message sent is not a closed loop.</h3><p>A case closes only when the responsible downstream workflow has been reconciled or a documented decision explains why no change is required.</p></div></div></section>

  <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Evaluation design</div><h2>Measure the denominator, workload and balancing measures.</h2></div></div><div className="table-wrap"><table><thead><tr><th>Measure</th><th>Minimum pilot requirement</th></tr></thead><tbody><tr><td>Baseline</td><td>Normally 8-12 weeks retrospective or prospective baseline where data quality permits.</td></tr><tr><td>Denominator</td><td>All eligible events/items/pathway episodes, not only successful interventions.</td></tr><tr><td>Intervention rate</td><td>Signals reviewed, accepted, rejected and unresolved.</td></tr><tr><td>Workload</td><td>Staff minutes by role, escalation burden and additional contacts.</td></tr><tr><td>Safety</td><td>Medication incidents, urgent supply, readmission/attendance signals where relevant, complaints and clinical concerns.</td></tr><tr><td>Benefit</td><td>Cash release, cost avoidance and capacity release kept separate.</td></tr><tr><td>Comparison</td><td>Pre/post, matched comparison or stepped implementation chosen before go-live.</td></tr></tbody></table></div></div></section>

  <section className="section"><div className="shell two-col"><div><div className="eyebrow">Stopping rules</div><h2>Reasons to pause or stop early.</h2><ul className="list-clean"><li>Unexpected medication safety signal or material patient harm concern</li><li>False-positive burden materially exceeds the agreed threshold</li><li>Required source data proves unreliable or incomplete</li><li>Workload transfer outweighs measured benefit</li><li>Clinical or information-governance conditions are no longer met</li><li>The intervention cannot be isolated enough to evaluate credibly</li></ul></div><div className="card"><span className="badge">Week 20</span><h3 style={{marginTop:12}}>The answer may legitimately be stop.</h3><p>The pilot is successful if it produces a trustworthy commissioning decision, including evidence that the opportunity is too small or too burdensome to pursue.</p></div></div></section>

  <section className="section pilot-funnel"><div className="shell two-col"><div><div className="eyebrow">Ready for technical discovery</div><h2>Next confirm whether the minimum data can actually be supplied.</h2><p className="lede">The data specification is deliberately minimal. It should be adapted to local systems rather than forcing an unnecessary replacement architecture.</p></div><div className="pilot-funnel-actions"><Link className="button primary" href="/data-specification">Open data specification</Link><Link className="button secondary" href="/pilot">Return to pilot overview</Link></div></div></section>
</>}
