import Link from "next/link";

const products = [
  {n:"01",tag:"Core workflow",title:"Medicine Loop",signal:"Cross-setting medication change",question:"Does every affected service reflect the same authorised medication change?",body:"Follow a hospital-stopped medicine across GP, pharmacy, care home and community care until every required downstream action is reconciled.",proof:"Backed by UK discharge and medicines-reconciliation evidence.",href:"/demo/medicine-loop"},
  {n:"02",tag:"Waste prevention",title:"WasteGuard",signal:"Repeat oversupply",question:"Should this repeat item actually be supplied again now?",body:"See how cumulative supply, expected use, stock and medication changes can trigger a proportionate human review before avoidable dispensing.",proof:"Backed by NHSBSA oversupply data and UK repeat-dispensing research.",href:"/demo/wasteguard"},
  {n:"03",tag:"Resource intelligence",title:"Medicines Resource Intelligence",signal:"Pathway capacity",question:"Which medicine-pathway opportunities deserve local measurement?",body:"Explore NHS and peer-reviewed examples showing how route, formulation, preparation and delivery model can alter nursing, pharmacy and treatment capacity.",proof:"Evidence-backed scenarios with source, setting and limitation shown.",href:"/demo/medicines-resource-intelligence"},
];

export default function DemoHubPage(){return <>
  <section className="page-head product-demo-head"><div className="shell"><div className="eyebrow">Interactive product experience</div><h1>Three medicines problems. Three workflows you can test now.</h1><p className="lede">Start with the operational problem, interact with the proposed Sitora workflow, inspect the evidence behind it, then see exactly what a controlled NHS pilot would still need to prove.</p><div className="hero-actions"><a className="button primary" href="#products">Choose a demo</a><Link className="button secondary" href="/pilot">See the pilot design</Link></div></div></section>

  <section className="section" id="products"><div className="shell demo-product-stack">{products.map(p=><article className="demo-product-row" key={p.title}><div className="demo-product-index"><span>{p.n}</span><small>{p.tag}</small></div><div className="demo-product-copy"><div className="meta-row"><span className="badge">{p.signal}</span><span>Evidence-linked</span></div><h2>{p.title}</h2><p className="demo-product-question">{p.question}</p><p>{p.body}</p><div className="demo-product-proof"><small>Evidence position</small><strong>{p.proof}</strong></div></div><div className="demo-product-action"><Link className="button primary" href={p.href}>Open demo →</Link><span>Interactive · no patient data</span></div></article>)}</div></section>

  <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Common proof standard</div><h2>Every demo separates evidence from the claim Sitora still has to earn.</h2></div></div><div className="evidence-triptych"><div className="card"><span className="badge">01 Proven already</span><h3>Is the underlying problem or intervention real?</h3><p>NHS, UK or peer-reviewed evidence establishes the mechanism and its relevance.</p></div><div className="card"><span className="badge">02 Sitora adds</span><h3>What operational layer is missing?</h3><p>Detection, ownership, workflow, reconciliation, prioritisation or whole-pathway measurement.</p></div><div className="card"><span className="badge">03 Pilot must prove</span><h3>Does it work safely here?</h3><p>Observed local outcomes, workload, safety, reusable capacity and independently validated financial effects.</p></div></div></div></section>

  <section className="section pilot-funnel"><div className="shell two-col"><div><div className="eyebrow">Next step after the demos</div><h2>Do not buy the claim. Test it.</h2><p className="lede">A controlled 20-week evaluation establishes baseline, introduces governed interventions and ends with a Scale / Modify / Stop decision.</p></div><div className="pilot-funnel-actions"><Link className="button primary" href="/pilot">Run a controlled pilot</Link><Link className="button secondary" href="/commissioner-summary">Commissioner summary</Link><small>Independent concept · not an NHS-endorsed service</small></div></div></section>
</>}
