import { dischargeInterventions, interventions } from "@/lib/interventions";

const productActions = [
  ["Medicine Loop","Medication change not propagated","Assign the accountable downstream service, preserve source conflict, reconcile local workflow, acknowledge closure.","Time-to-close, unresolved discrepancy rate, obsolete supply prevented, safety."],
  ["WasteGuard","Repeat may not be needed","Present the oversupply/stock/change signal for human review before dispensing.","Reviewed signals, deferred supply, workload, missed-needed-supply rate, verified cost avoidance."],
  ["Resource Intelligence","Necessary treatment uses high resource","Compare clinically appropriate alternatives, approve locally, measure before/after pathway resource.","Staff minutes, chair/bed time, unused dose, patient impact, validated financial effect."],
];

export default function InterventionsPage(){return <>
<section className="page-head"><div className="shell"><div className="eyebrow">Intervention intelligence</div><h1>Every signal needs an owner, a governed action and a measurable close.</h1><p className="lede">Sitora does not treat detection as success. Each product has its own intervention logic, safety boundary and proof of completion.</p></div></section>
<section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Product action model</div><h2>Different problems require different interventions.</h2></div></div><div className="evidence-triptych">{productActions.map(([title,signal,action,measure])=><article className="card" key={title}><span className="badge">{title}</span><h3 style={{marginTop:12}}>{signal}</h3><p><strong>Action:</strong> {action}</p><p><strong>Proof:</strong> {measure}</p></article>)}</div></div></section>
<section className="section"><div className="shell"><div className="callout"><strong>Core rule</strong><p>No intervention counts because a notification was sent, a flag was generated or a pathway was modelled. The relevant downstream action and outcome must be observed.</p></div></div></section>
<section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Measurement chain</div><h2>Four tests before benefit is claimed.</h2></div></div><div className="metric-grid"><div className="metric"><span className="badge">1</span><strong>Signal</strong><h3>Problem validated</h3><small>Is the discrepancy, supply risk or resource opportunity real?</small></div><div className="metric"><span className="badge">2</span><strong>Action</strong><h3>Owner acted</h3><small>Did the responsible professional or service complete the governed action?</small></div><div className="metric"><span className="badge">3</span><strong>Outcome</strong><h3>Workflow changed</h3><small>Was the medicine state, dispensing outcome or treatment pathway actually different?</small></div><div className="metric"><span className="badge">4</span><strong>Value</strong><h3>Benefit classified</h3><small>Safety, cash, avoidance and capacity remain separate.</small></div></div></div></section>
<section className="section"><div className="shell"><details className="faq-item"><summary>Legacy discharge and wider NHS intervention library</summary><div className="faq-answer"><p>These remain supporting research and future expansion opportunities rather than current Sitora medicines products.</p><div className="faq-list">{dischargeInterventions.map((item,index)=><details className="faq-item" key={item.bottleneck}><summary><span>{item.bottleneck}</span><span className="badge">Research {index+1}</span></summary><div className="faq-answer"><p><strong>Signal:</strong> {item.signal}</p><p><strong>Owners:</strong> {item.primaryOwners.join(" · ")}</p><p><strong>Intervention:</strong> {item.intervention}</p><p><strong>Verification:</strong> {item.verification}</p></div></details>)}</div><div className="card-grid" style={{marginTop:18}}>{interventions.map(item=><article className="card" key={item.slug}><div className="meta-row"><span className="badge">{item.domain}</span><span>Evidence: {item.evidence}</span></div><h3>{item.title}</h3><p>{item.problem}</p><p><strong>Intervention:</strong> {item.intervention}</p></article>)}</div></div></details></div></section>
<section className="section"><div className="shell quote">Detection creates an obligation to investigate. Only a completed, safe and measured downstream action creates evidence of value.</div></section>
</>}
