import { dischargeInterventions, interventions } from "@/lib/interventions";

export default function InterventionsPage(){
  return <>
    <section className="page-head"><div className="shell"><div className="eyebrow">Intervention intelligence</div><h1>Every bottleneck needs an owner, an action and a measurable test.</h1><p className="lede">The intervention layer turns a resource-loss signal into something operational: who acts, what changes, what success looks like and what evidence is required before claiming benefit.</p></div></section>

    <section className="section"><div className="shell"><div className="callout"><strong>Core rule</strong><p>Do not claim savings because an intervention was introduced. Show that the targeted process changed, then the patient pathway changed, then that usable resource was actually released.</p></div></div></section>

    <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Measurement chain</div><h2>Four tests before a pound sign appears.</h2></div></div><div className="metric-grid">
      <div className="metric"><span className="badge">1</span><strong>Process</strong><h3>Dependency changed</h3><small>Did the targeted step become faster or more reliable?</small></div>
      <div className="metric"><span className="badge">2</span><strong>Patient</strong><h3>Pathway changed</h3><small>Did the patient move through the pathway sooner and safely?</small></div>
      <div className="metric"><span className="badge">3</span><strong>Capacity</strong><h3>Resource released</h3><small>Was usable bed, chair, pharmacy, nursing or appointment capacity created?</small></div>
      <div className="metric"><span className="badge">4</span><strong>Value</strong><h3>Benefit classified</h3><small>Cash, cost avoidance and productivity remain separate.</small></div>
    </div></div></section>

    <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Discharge action matrix</div><h2>Open the bottleneck that needs action.</h2></div><p>Each intervention includes owner, first action, leading indicator, outcome measure, verification rule and guardrails.</p></div><div className="faq-list">{dischargeInterventions.map((item,index)=><details className="faq-item" key={item.bottleneck}><summary><span>{item.bottleneck}</span><span className="badge">Priority {index+1}</span></summary><div className="faq-answer"><p><strong>Signal:</strong> {item.signal}</p><p><strong>Owners:</strong> {item.primaryOwners.join(" · ")}</p><p><strong>Intervention:</strong> {item.intervention}</p><h3>First actions</h3><ul className="list-clean">{item.firstActions.map((a)=><li key={a}>{a}</li>)}</ul><h3>Leading indicators</h3><ul className="list-clean">{item.leadingIndicators.map((m)=><li key={m}>{m}</li>)}</ul><h3>Outcome measures</h3><ul className="list-clean">{item.outcomeMeasures.map((m)=><li key={m}>{m}</li>)}</ul><p><strong>Verification:</strong> {item.verification}</p><p><strong>Measurement horizon:</strong> {item.expectedHorizon}</p><h3>Guardrails</h3><ul className="list-clean">{item.guardrails.map((g)=><li key={g}>{g}</li>)}</ul></div></details>)}</div></div></section>

    <section className="section"><div className="shell"><details className="faq-item"><summary>Pilot measurement standard</summary><div className="faq-answer"><div className="table-wrap"><table><thead><tr><th>Stage</th><th>Minimum requirement</th></tr></thead><tbody><tr><td>Baseline</td><td>8-12 weeks pre-intervention data where available</td></tr><tr><td>Population</td><td>Clear inclusion criteria and denominator</td></tr><tr><td>Process</td><td>Timestamped dependency data</td></tr><tr><td>Outcome</td><td>Relevant pathway and capacity outcome</td></tr><tr><td>Safety</td><td>Readmissions, incidents, failed pathways and concerns</td></tr><tr><td>Comparison</td><td>Pre/post, matched site or stepped implementation</td></tr><tr><td>Value</td><td>Cash, avoidance and capacity shown separately</td></tr><tr><td>Decision</td><td>Continue, modify or stop rule set before launch</td></tr></tbody></table></div></div></details></div></section>

    <section className="section"><div className="shell"><details className="faq-item"><summary>Other intervention opportunities already in the library</summary><div className="faq-answer"><div className="card-grid">{interventions.map((item)=><article className="card" key={item.slug}><div className="meta-row"><span className="badge">{item.domain}</span><span>Evidence: {item.evidence}</span></div><h3>{item.title}</h3><p>{item.problem}</p><p><strong>Intervention:</strong> {item.intervention}</p></article>)}</div></div></details></div></section>

    <section className="section"><div className="shell quote">Intervention intelligence turns “we found a problem” into “this person owns the next action, this metric should move, and this is how we will know whether the resource was really recovered.”</div></section>
  </>;
}
