const phases = [["0-4 weeks","Mobilise","Confirm sponsor, sites, governance, data flows, safety boundaries and baseline definitions."],["5-8 weeks","Baseline","Measure cross-setting medication discrepancies, repeat-supply signals, pathway resource use and workload."],["9-16 weeks","Intervene","Run controlled, human-reviewed workflows in shadow mode first, then approved live use."],["17-20 weeks","Evaluate","Verify closure, avoided supply, resource recovery, safety and net operational effect."]];

const workstreams = [
  ["Medicine Loop","Close medication changes across organisations.","Hospital discharge and other cross-setting changes affecting GP, pharmacy, care-home or community workflows.","Open-loop rate, time-to-reconcile, downstream acknowledgements, discrepancies resolved, obsolete supply prevented and safety."],
  ["WasteGuard","Prevent repeat supply that may no longer be required.","Selected repeat-medicine cohorts where cumulative supply, stock or change history can be assessed safely.","Reviews triggered, supplies deferred, dispensing outcome, intervention workload, safety and verified cost avoidance."],
  ["Medicines Resource Intelligence","Identify and verify lower-resource clinically appropriate pathways.","Selected high-volume or resource-intensive injectable, SACT or preparation pathways.","Pharmacy/nursing minutes, chair or bed capacity, unused doses, pathway cost, patient impact and safety."]
];

export default function BusinessCasePage(){return <>
<section className="page-head"><div className="shell"><div className="eyebrow">Pilot business case</div><h1>Can Sitora close medicines loops, prevent avoidable supply and recover measurable NHS resource safely?</h1><p className="lede">The 20-week pilot tests three distinct products with one evidence standard: baseline first, governed action second, verified outcome last.</p></div></section>
<section className="section"><div className="shell metric-grid"><div className="metric"><span className="badge">Duration</span><strong>20 weeks</strong><h3>Full evaluation cycle</h3><small>Mobilise, baseline, intervene and verify.</small></div><div className="metric"><span className="badge">Products</span><strong>3</strong><h3>Separate hypotheses</h3><small>Medication continuity, avoidable supply and pathway resource use.</small></div><div className="metric"><span className="badge">Sites</span><strong>1 + network</strong><h3>Acute + community</h3><small>Enough scope to test cross-boundary medicines flows.</small></div><div className="metric"><span className="badge">Endpoint</span><strong>Decision</strong><h3>Scale / modify / stop</h3><small>No automatic assumption of success.</small></div></div></section>
<section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Why Sitora exists</div><h2>Existing systems hold data. Sitora tests whether the next action is owned and closed.</h2></div></div><div className="two-col"><div className="card"><h3>Current environment</h3><p>Medication changes, repeat authorisations, dispensing, administration and pathway activity can sit across different systems and organisations. Visibility does not guarantee that downstream work is complete.</p></div><div className="card"><h3>Proposed layer</h3><p>Sitora creates accountable signals and events around those systems, routes action to the right professional and records whether the loop, supply decision or resource opportunity was actually resolved.</p></div></div></div></section>
<section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Three workstreams</div><h2>Three products. Three different outcomes.</h2></div></div><div className="card-grid">{workstreams.map(([title,aim,pop,outcome])=><article className="card" key={title}><span className="badge">Pilot stream</span><h3 style={{marginTop:12}}>{title}</h3><p>{aim}</p><details><summary>View scope and outcomes</summary><p><strong>Population:</strong> {pop}</p><p><strong>Primary outcomes:</strong> {outcome}</p></details></article>)}</div></div></section>
<section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Delivery</div><h2>Shadow mode before live change.</h2></div></div><div className="process">{phases.map(([time,title,body])=><div className="process-step" key={title}><span>{time}</span><h3>{title}</h3><p>{body}</p></div>)}</div></div></section>
<section className="section"><div className="shell two-col"><div><div className="eyebrow">Success</div><h2>What would justify scale?</h2><ul className="list-clean"><li><strong>Medicine Loop:</strong> fewer unresolved cross-setting discrepancies and faster safe closure.</li><li><strong>WasteGuard:</strong> avoidable dispensing prevented without missed essential supply.</li><li><strong>Resource Intelligence:</strong> observed reusable capacity or validated cost effect.</li><li><strong>Across all three:</strong> manageable workload, traceable outcomes and no unacceptable safety deterioration.</li></ul></div><div className="card"><span className="badge">Verification rule</span><h3 style={{marginTop:12}}>Different benefits stay separate.</h3><p>Clinical discrepancy resolution, cash release, cost avoidance and capacity release are not interchangeable. Each product keeps its own denominator and outcome definition.</p></div></div></section>
<section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Governance</div><h2>Designed around controlled deployment.</h2></div><p>Exact regulatory applicability depends on intended use and deployment architecture.</p></div><div className="card-grid"><details className="card"><summary><strong>Clinical safety</strong></summary><p>Named clinical leadership, hazard logging, escalation rules, human review and no autonomous prescribing changes.</p></details><details className="card"><summary><strong>Information governance</strong></summary><p>DPIA, data-flow mapping, minimisation, role-based access, provenance and audit logging.</p></details><details className="card"><summary><strong>Technical assurance</strong></summary><p>Read-only integration first, visible source conflicts, no silent overwrite and explicit acknowledgement states.</p></details><details className="card"><summary><strong>Finance and evaluation</strong></summary><p>Pre-agreed outcomes and finance validation before any cash-releasing claim is reported.</p></details></div></div></section>
<section className="section"><div className="shell two-col"><div><div className="eyebrow">Approval ask</div><h2>What the NHS partner would approve.</h2><ul className="list-clean"><li>20-week controlled medicines pilot</li><li>One acute provider plus selected GP/pharmacy/care partners</li><li>Named clinical, pharmacy, digital, IG, finance and evaluation leads</li><li>Minimum agreed data access</li><li>Shadow-mode validation before live workflow intervention</li><li>Pre-agreed Scale / Modify / Stop thresholds</li></ul></div><div className="card"><span className="badge">Next document</span><h3 style={{marginTop:12}}>Technical implementation</h3><p>The technical plan defines source systems, minimum data, event ownership, acknowledgement states, audit requirements and deployment gates.</p><a className="button primary" href="/technical-implementation">Open technical plan</a></div></div></section>
</>}
