const phases = [["0-4 weeks","Mobilise","Confirm sponsor, sites, governance, data access and baseline definitions."],["5-8 weeks","Baseline","Measure current repeat supply, injectable pathways, unused doses and resource inputs."],["9-16 weeks","Intervene","Run controlled, human-reviewed interventions."],["17-20 weeks","Evaluate","Verify net resource recovery, safety and operational impact."]];

const workstreams = [
  ["Medicine Loop","Prevent avoidable repeat supply before dispensing.","Selected stable repeat-medicine cohorts across GP practices and community pharmacies.","Avoided items, discrepancies resolved, workload change, safety and patient experience."],
  ["Medicines Resource Intelligence","Reduce avoidable pharmacy, nursing, aseptic, chair and bed resource use.","Selected high-volume or resource-intensive injectable/SACT pathways.","Preparation, staff minutes, chair/bed capacity, unused doses, pathway cost and safety."],
  ["Prepared-but-unused medicines","Turn discarded preparations into a root-cause dataset and reduce recurrence.","Selected prepared medicines not administered during the pilot period.","Discard rate, value, repeated causes, preventable fraction and post-intervention change."]
];

export default function BusinessCasePage() {
  return (
    <>
      <section className="page-head"><div className="shell"><div className="eyebrow">Pilot business case</div><h1>Can medicines intelligence recover measurable NHS resource without compromising care?</h1><p className="lede">This 20-week pilot is designed to answer that question with a baseline, governed interventions and verified outcomes.</p></div></section>

      <section className="section"><div className="shell metric-grid">
        <div className="metric"><span className="badge">Duration</span><strong>20 weeks</strong><h3>Full evaluation cycle</h3><small>Mobilise, baseline, intervene and verify.</small></div>
        <div className="metric"><span className="badge">Scope</span><strong>3</strong><h3>Medicines workstreams</h3><small>Repeat supply, pathway optimisation and unused preparations.</small></div>
        <div className="metric"><span className="badge">Sites</span><strong>1 + network</strong><h3>Acute + primary/community</h3><small>Enough scope to test cross-boundary medicines flows.</small></div>
        <div className="metric"><span className="badge">Endpoint</span><strong>Decision</strong><h3>Scale / modify / stop</h3><small>The pilot must produce a commissioning answer.</small></div>
      </div></section>

      <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Why now</div><h2>The information loop is incomplete.</h2></div></div><div className="two-col"><div className="card"><h3>Today</h3><p>Prescribing records intent, dispensing records supply, and hospital systems record activity. Those signals are often separated, so the next supply decision and the total resource pathway are not continuously informed by what happened previously.</p></div><div className="card"><h3>Proposed</h3><p>Sitora sits above existing systems, identifies candidate resource-loss events, routes clinically significant cases to authorised professionals and verifies whether the expected resource was actually recovered.</p></div></div></div></section>

      <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Three workstreams</div><h2>One medicines programme.</h2></div></div><div className="card-grid">{workstreams.map(([title,aim,pop,outcome]) => <article className="card" key={title}><span className="badge">Pilot stream</span><h3 style={{marginTop:12}}>{title}</h3><p>{aim}</p><details><summary>View scope and outcomes</summary><p><strong>Population:</strong> {pop}</p><p><strong>Primary outcomes:</strong> {outcome}</p></details></article>)}</div></div></section>

      <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Delivery</div><h2>Baseline before intervention. Verification before claims.</h2></div></div><div className="process">{phases.map(([time,title,body]) => <div className="process-step" key={title}><span>{time}</span><h3>{title}</h3><p>{body}</p></div>)}</div></div></section>

      <section className="section"><div className="shell two-col"><div><div className="eyebrow">Success</div><h2>What would justify scale?</h2><ul className="list-clean"><li><strong>Safe:</strong> no unacceptable deterioration in clinical outcomes, adherence or access.</li><li><strong>Measurable:</strong> intervention and outcome are traceable.</li><li><strong>Net positive:</strong> verified resource value exceeds intervention cost.</li><li><strong>Operationally acceptable:</strong> no unsustainable additional workload.</li><li><strong>Reproducible:</strong> data and workflow can support a larger rollout.</li></ul></div><div className="card"><span className="badge">Verification rule</span><h3 style={{marginTop:12}}>Separate the benefit types.</h3><p>Cash-releasing savings, cost avoidance and capacity release are reported separately. Released capacity only counts when it is genuinely available for another patient or activity.</p></div></div></section>

      <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Governance</div><h2>Designed for NHS deployment.</h2></div><p>Exact regulatory applicability depends on intended use and must be confirmed before deployment.</p></div><div className="card-grid">
        <details className="card"><summary><strong>Clinical safety</strong></summary><p>Named clinical leadership, formal clinical-risk management, hazard logging, escalation rules and human review of clinically significant interventions.</p></details>
        <details className="card"><summary><strong>Information governance</strong></summary><p>DPIA, data-flow mapping, data minimisation, role-based access, audit logging and agreed retention controls.</p></details>
        <details className="card"><summary><strong>Evaluation</strong></summary><p>Named analytical lead, pre-agreed baseline and comparison method, patient and safety outcomes, and transparent limitations.</p></details>
        <details className="card"><summary><strong>Finance validation</strong></summary><p>Provider or ICB finance sign-off before any claimed cash-releasing benefit is reported.</p></details>
      </div></div></section>

      <section className="section"><div className="shell two-col"><div><div className="eyebrow">Indicative team</div><h2>Enough resource to produce a trustworthy answer.</h2><ul className="list-clean"><li>Clinical/pharmacy lead: 0.2-0.3 WTE</li><li>Medicines optimisation pharmacist: 0.5 WTE</li><li>Data/analytics: 0.5-1.0 WTE</li><li>Product/integration engineering: 1.0-1.5 WTE</li><li>Clinical safety / IG: sessional</li><li>Finance/evaluation: 0.1-0.2 WTE</li></ul></div><div className="card"><span className="badge">Cost envelope</span><h3 style={{marginTop:12}}>Price after technical discovery.</h3><p>A governed pilot is likely to sit in the broad tens-to-low-hundreds-of-thousands range depending on integration complexity, backfill, data engineering and reusable infrastructure. This is a planning assumption, not a quote.</p></div></div></section>

      <section className="section"><div className="shell two-col"><div><div className="eyebrow">Decision rule</div><h2>Pre-agree the answer categories.</h2><ul className="list-clean"><li><strong>Scale:</strong> safe, positive net benefit and reproducible operation.</li><li><strong>Modify:</strong> value signal exists but targeting, workflow or data quality needs redesign.</li><li><strong>Stop:</strong> no credible opportunity, negative net benefit or unacceptable burden.</li></ul></div><div className="card"><span className="badge">Approval ask</span><h3 style={{marginTop:12}}>What the NHS partner approves</h3><ul className="list-clean"><li>20-week medicines pilot</li><li>Participating sites and accountable leads</li><li>Minimum agreed data access</li><li>Governed human-reviewed interventions</li><li>Pre-agreed benefit definitions and success thresholds</li></ul></div></div></section>
    </>
  );
}
