import Link from "next/link";

const fields = [
  ["Patient linkage","Stable pseudonymous person identifier","All","Link events across settings without exposing unnecessary demographics.","Pseudonymised preferred","Required"],
  ["Medication identity","dm+d concept / local code, name, strength, form","All","Match the same medicine across prescribing, dispensing and administration systems.","Clinical data","Required"],
  ["Medication state","Active / stopped / changed / held plus effective timestamp","Medicine Loop","Establish the latest authorised state and detect conflicts.","Clinical data","Required"],
  ["Change provenance","Source organisation, author role, timestamp, reason where available","Medicine Loop","Show who changed what, when and why; support reconciliation rather than silent overwrite.","Clinical data","Required"],
  ["Downstream owner","GP / pharmacy / care home / community / other responsible service","Medicine Loop","Assign acknowledgement and reconciliation to the right workflow.","Operational","Required"],
  ["Acknowledgement / closure","Received, reviewed, reconciled, rejected, reason, timestamps","Medicine Loop","Measure whether the medication-change loop actually closed.","Operational","Required"],
  ["Prescription / repeat state","Issue date, quantity, repeat status, prescribed dose where available","WasteGuard","Establish what was authorised and whether an old repeat remains active.","Clinical/operational","Required"],
  ["Dispensing history","Dispensed date, quantity, status, pharmacy identifier","WasteGuard","Calculate cumulative supply and determine whether another item is plausibly required.","Operational","Required"],
  ["Patient-held stock/use","Structured confirmation or locally available proxy","WasteGuard","Improve precision where stock accumulation or non-use is suspected.","Patient-reported / operational","Optional initially"],
  ["Pathway episode","Medicine, indication/pathway, route, formulation, location, administration date","Resource Intelligence","Define the treatment pathway being compared.","Clinical/operational","Required"],
  ["Staff resource","Preparation / administration minutes by relevant staff group","Resource Intelligence","Measure actual resource change rather than assuming published effects apply locally.","Operational","Required for selected pathway"],
  ["Facility resource","Chair time, bed time or treatment-space duration","Resource Intelligence","Measure reusable capacity where relevant.","Operational","Required if claimed"],
  ["Medicine/resource cost","Acquisition cost, consumables and agreed local costing basis","Resource Intelligence / WasteGuard","Classify financial effect transparently.","Finance","Required for £ claims"],
  ["Unused preparation","Prepared, not administered, reason, disposition and value","Resource Intelligence","Measure avoidable preparation loss and root causes.","Operational","Optional workstream"],
  ["Safety / balancing","Incident, urgent supply, escalation, relevant attendance/readmission proxy","All","Ensure apparent productivity does not conceal harm or access problems.","Clinical/operational","Required"]
];

export default function DataSpecificationPage(){return <>
  <section className="page-head"><div className="shell"><div className="eyebrow">Pilot readiness pack · minimum data specification</div><h1>Use the minimum data needed to answer the pilot questions safely.</h1><p className="lede">This is a logical data specification, not a demand for one particular NHS system or API. Local discovery should map these fields onto the provider's existing EPR, GP, pharmacy, eMAR, prescribing, dispensing, finance and pathway systems.</p><div className="hero-actions"><Link className="button primary" href="/pilot-protocol">Pilot protocol</Link><Link className="button secondary" href="/technical-implementation">Technical implementation</Link></div></div></section>

  <section className="section"><div className="shell metric-grid"><div className="metric"><span className="badge">Principle</span><strong>Minimum</strong><h3>Data minimisation</h3><small>Collect only fields required for detection, ownership, evaluation and safety.</small></div><div className="metric"><span className="badge">Identity</span><strong>Pseudo</strong><h3>Pseudonymise where possible</h3><small>Identifiable access only where the live clinical workflow genuinely requires it.</small></div><div className="metric"><span className="badge">Provenance</span><strong>Always</strong><h3>Source stays visible</h3><small>Conflicts are reconciled, never silently overwritten.</small></div><div className="metric"><span className="badge">Refresh</span><strong>Fit</strong><h3>Frequency follows use case</h3><small>Near-live only where needed; batch is acceptable for many evaluation measures.</small></div></div></section>

  <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Logical field set</div><h2>What the pilot needs and why.</h2></div><p>Exact names, formats and interfaces are resolved during local technical discovery.</p></div><div className="table-wrap"><table><thead><tr><th>Data domain</th><th>Minimum fields</th><th>Product</th><th>Purpose</th><th>Class</th><th>Priority</th></tr></thead><tbody>{fields.map(([d,f,purposeProduct,purpose,klass,priority])=><tr key={d}><td><strong>{d}</strong></td><td>{f}</td><td>{purposeProduct}</td><td>{purpose}</td><td>{klass}</td><td>{priority}</td></tr>)}</tbody></table></div></div></section>

  <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Likely NHS source categories</div><h2>Map locally rather than assuming one national architecture.</h2></div></div><div className="card-grid"><article className="card"><span className="badge">Primary care</span><h3 style={{marginTop:12}}>GP prescribing / repeat record</h3><p>Medication list, repeat state, issue history, medication review and reconciliation outcomes where available.</p></article><article className="card"><span className="badge">Acute / specialist</span><h3 style={{marginTop:12}}>EPR, ePMA and discharge</h3><p>Authorised medication changes, discharge medicines, administration and pathway activity.</p></article><article className="card"><span className="badge">Pharmacy</span><h3 style={{marginTop:12}}>Dispensing / DMS / local systems</h3><p>Actual supply, quantity, timing, interventions and acknowledgement workflow.</p></article><article className="card"><span className="badge">Care</span><h3 style={{marginTop:12}}>eMAR / care-home workflow</h3><p>Administration state, stock/use signals and reconciliation actions where included.</p></article><article className="card"><span className="badge">Pathway</span><h3 style={{marginTop:12}}>SACT / aseptic / treatment systems</h3><p>Preparation, route, administration, chair/bed use, cancellations and unused preparations.</p></article><article className="card"><span className="badge">Value</span><h3 style={{marginTop:12}}>Finance / costing / workforce</h3><p>Local cost basis and staff/capacity measures required to validate benefit claims.</p></article></div></div></section>

  <section className="section"><div className="shell two-col"><div><div className="eyebrow">Refresh model</div><h2>Not everything needs real-time integration.</h2><ul className="list-clean"><li><strong>Medication-change events:</strong> near-live or sufficiently prompt to support safe downstream reconciliation.</li><li><strong>Dispensing / repeat signals:</strong> daily or event-driven where practical.</li><li><strong>Resource pathway measures:</strong> batch extracts may be adequate for baseline and evaluation.</li><li><strong>Finance validation:</strong> periodic agreed extracts are usually sufficient.</li><li><strong>Safety outcomes:</strong> cadence agreed with the clinical safety/evaluation team.</li></ul></div><div className="card"><span className="badge">Fallback principle</span><h3 style={{marginTop:12}}>Missing data should reduce confidence, not trigger invention.</h3><p>If a required field is unavailable, the pilot should either use an agreed proxy with its limitation recorded, narrow the use case, or classify the event as not evaluable.</p></div></div></section>

  <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Access and governance</div><h2>Separate analytics access from clinical-action access.</h2></div></div><div className="evidence-triptych"><article className="card"><span className="badge">Analytics</span><h3>Prefer pseudonymised datasets</h3><p>Baseline, opportunity sizing and most evaluation work should not require direct identifiers.</p></article><article className="card"><span className="badge">Clinical workflow</span><h3>Minimum identifiable access</h3><p>Where a professional must act on an individual case, access should be role-based, auditable and limited to that workflow.</p></article><article className="card"><span className="badge">Audit</span><h3>Provenance is part of the data model</h3><p>Source, timestamp, author/role, action and resolution history should be retained according to the agreed governance model.</p></article></div></div></section>

  <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Technical discovery acceptance</div><h2>Before shadow mode begins, answer these questions.</h2></div></div><ul className="list-clean"><li>Can the same patient and medicine be linked safely across participating systems?</li><li>Can an authorised medication change be distinguished from a local stale state?</li><li>Can the responsible downstream organisation or workflow be identified?</li><li>Can actual dispensing be distinguished from prescribing intent?</li><li>Can the selected resource pathway be measured consistently before and after intervention?</li><li>Can staff workload and safety balancing measures be captured?</li><li>Can finance validate the costing method used for any £ claim?</li><li>Can every data item and decision be traced back to its source?</li></ul></div></section>

  <section className="section pilot-funnel"><div className="shell two-col"><div><div className="eyebrow">Pilot readiness gate</div><h2>If the minimum fields cannot be supplied reliably, narrow the pilot before adding complexity.</h2><p className="lede">A smaller evaluable cohort is more valuable than a large pilot built on uncertain medication state or untraceable benefit assumptions.</p></div><div className="pilot-funnel-actions"><Link className="button primary" href="/pilot-protocol">Review protocol</Link><Link className="button secondary" href="/business-case">Business case</Link></div></div></section>
</>}
