import { rankedOpportunities, opportunityScore } from "@/lib/opportunities";

function scoreBar(label:string,value:number){return <div className="score-row" key={label}><div className="score-label"><span>{label}</span><strong>{value}</strong></div><div className="score-track"><div className="score-fill" style={{width:`${value}%`}} /></div></div>}

export default function OpportunitiesPage(){const top=rankedOpportunities.slice(0,5);return <>
<section className="page-head"><div className="shell"><div className="eyebrow">Opportunity Register</div><h1>Prioritise what Sitora should test next, without confusing scale with recoverability.</h1><p className="lede">The active medicines programme has three product lenses. The wider NHS register remains a research pipeline for future validation and expansion.</p></div></section>
<section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Current medicines lenses</div><h2>Where an opportunity belongs determines how it is tested.</h2></div></div><div className="evidence-triptych"><article className="card"><span className="badge">Medicine Loop</span><h3 style={{marginTop:12}}>Continuity and reconciliation</h3><p>Opportunities involving medication changes that fail to propagate or close across organisations.</p></article><article className="card"><span className="badge">WasteGuard</span><h3 style={{marginTop:12}}>Avoidable supply</h3><p>Opportunities involving cumulative oversupply, stock mismatch or repeat items that may not be required.</p></article><article className="card"><span className="badge">Resource Intelligence</span><h3 style={{marginTop:12}}>Pathway resource</h3><p>Opportunities involving route, formulation, preparation, workforce time, chair/bed use or unused medicines.</p></article></div></div></section>
<section className="section"><div className="shell"><div className="callout"><strong>How ranking works</strong><p>Scale, evidence, recoverability, readiness and measurability are scored separately. A high score prioritises investigation; it does not mean money is already available to save.</p></div></div></section>
<section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Highest current research priorities</div><h2>Large signals with evidence, an actionable intervention and a way to verify change.</h2></div><p>These may include medicines and wider NHS resource domains.</p></div><div className="card-grid">{top.map((item,index)=><article className="card" key={item.id}><div className="meta-row"><span className="badge">#{index+1}</span><span>{item.domain}</span><span>{item.benefitType}</span></div><div className="evidence-value">{opportunityScore(item)}</div><h3>{item.title}</h3><p>{item.opportunityStatement}</p><p><strong>Pilot readiness:</strong> {item.pilotReadiness}</p></article>)}</div></div></section>
<section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Full research pipeline</div><h2>Every opportunity states what is known, what is uncertain and what would prove value.</h2></div></div><div className="opportunity-stack">{rankedOpportunities.map((item,index)=><article className="card opportunity-card" key={item.id}><div className="opportunity-head"><div><div className="meta-row"><span className="badge">Rank {index+1}</span><span>{item.domain}</span><span>{item.benefitType}</span><span>Evidence: {item.evidence}</span></div><h2>{item.title}</h2></div><div className="opportunity-score"><strong>{opportunityScore(item)}</strong><small>priority score</small></div></div><div className="opportunity-grid"><div><h3>Observed signal</h3><p>{item.observedSignal}</p><h3>Opportunity</h3><p>{item.opportunityStatement}</p><h3>Operational owner</h3><p>{item.owner}</p><h3>Intervention</h3><p>{item.intervention}</p></div><div>{scoreBar("Scale",item.scores.scale)}{scoreBar("Evidence",item.scores.evidence)}{scoreBar("Recoverability",item.scores.recoverability)}{scoreBar("Readiness",item.scores.readiness)}{scoreBar("Measurability",item.scores.measurability)}<p><strong>Pilot readiness:</strong> {item.pilotReadiness}</p></div></div><div className="opportunity-grid"><div><h3>Minimum data needed</h3><ul className="list-clean">{item.firstDataNeeded.map(x=><li key={x}>{x}</li>)}</ul></div><div><h3>What proves recovery</h3><ul className="list-clean">{item.verification.map(x=><li key={x}>{x}</li>)}</ul></div><div><h3>Safety / interpretation guardrails</h3><ul className="list-clean">{item.safeguards.map(x=><li key={x}>{x}</li>)}</ul></div></div><a className="source-link" href={item.sourceUrl} target="_blank" rel="noreferrer">Source: {item.sourceLabel} ↗</a></article>)}</div></div></section>
<section className="section"><div className="shell quote">The register is a research pipeline. Sitora's current products are the governed mechanisms used to turn selected medicines opportunities into measurable local outcomes.</div></section>
</>}
