import Link from "next/link";

export default function TechnicalImplementationPage(){
  return <>
    <section className="page-head"><div className="shell"><div className="eyebrow">Technical implementation</div><h1>Integrate narrowly. Preserve provenance. Prove closure.</h1><p className="lede">The first deployment should sit around existing NHS medication and workflow systems, consume only the data needed for the pilot, and create an auditable action layer rather than another unrestricted medication database.</p><div className="hero-actions"><Link className="button primary" href="/pilot">Pilot design</Link><Link className="button secondary" href="/demo">See it working</Link></div></div></section>

    <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Architecture principle</div><h2>Read from source systems. Create owned events. Write back only through governed workflows.</h2></div></div><div className="process">{[["01","Source","Medication, prescribing, dispensing, discharge and selected operational systems."],["02","Normalise","Map patient, medicine, event, organisation, provenance and timestamp into a common event model."],["03","Detect","Apply deterministic rules and approved analytics to identify conflicts, oversupply signals or resource opportunities."],["04","Route","Create an accountable task for the responsible service or professional."],["05","Close","Record acknowledgement, reconciliation, outcome and verification without erasing source history."]].map(([n,t,b])=><div className="process-step" key={t}><span>{n}</span><h3>{t}</h3><p>{b}</p></div>)}</div></div></section>

    <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Minimum data model</div><h2>Enough structure to make the loop auditable.</h2></div></div><div className="card-grid"><article className="card"><span className="badge">Medication state</span><h3 style={{marginTop:12}}>What is believed to be active?</h3><p>Medicine identifier, strength, formulation, route, dose, frequency, status, source organisation, source system and last verified time.</p></article><article className="card"><span className="badge">Change event</span><h3 style={{marginTop:12}}>What changed?</h3><p>Start, stop, dose, route or formulation change; author; clinical role; organisation; reason; effective time; intended duration; follow-up and provenance.</p></article><article className="card"><span className="badge">Supply state</span><h3 style={{marginTop:12}}>What has been prescribed or dispensed?</h3><p>Repeat status, prescription date, dispense status, quantity, partial supply, owing, cancellation and next expected cycle where available.</p></article><article className="card"><span className="badge">Workflow state</span><h3 style={{marginTop:12}}>Who owns the next action?</h3><p>Recipient organisation, accountable role, task, status, acknowledgement, reconciliation result, conflict reason and closure timestamp.</p></article></div></div></section>

    <section className="section"><div className="shell two-col"><div><div className="eyebrow">Integration sources</div><h2>Likely pilot interfaces.</h2><ul className="list-clean"><li><strong>Primary care:</strong> current medication and repeat state</li><li><strong>Acute/EPR:</strong> admission, inpatient change and discharge medication events</li><li><strong>Community pharmacy:</strong> dispensing and supply state</li><li><strong>Shared care record:</strong> cross-setting visibility and provenance where available</li><li><strong>Care home/eMAR:</strong> administration and local medication state for included residents</li><li><strong>Pharmacy/aseptic systems:</strong> preparation timestamps and selected resource measures</li></ul></div><div className="card"><span className="badge">Interoperability</span><h3 style={{marginTop:12}}>Standards first where interfaces permit.</h3><p>The pilot should map to NHS-supported interoperability standards and preserve source identifiers and provenance. The exact interface pattern depends on the participating systems and approved access routes; the first technical discovery should confirm what is available rather than assume universal API access.</p></div></div></section>

    <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Deployment sequence</div><h2>Move from synthetic to shadow to controlled intervention.</h2></div></div><div className="metric-grid"><div className="metric"><span className="badge">Stage 1</span><strong>Synthetic</strong><h3>Workflow alpha</h3><small>Validate event model, permissions, task states and user journeys without patient data.</small></div><div className="metric"><span className="badge">Stage 2</span><strong>Shadow</strong><h3>Live data, no action</h3><small>Measure signal frequency, data quality and false positives without changing clinical workflow.</small></div><div className="metric"><span className="badge">Stage 3</span><strong>Controlled</strong><h3>Human-reviewed action</h3><small>Enable only approved interventions for a defined cohort and monitored use cases.</small></div><div className="metric"><span className="badge">Stage 4</span><strong>Evaluate</strong><h3>Verify outcomes</h3><small>Compare baseline, workload, safety and resource effects before any scale decision.</small></div></div></div></section>

    <section className="section"><div className="shell two-col"><div><div className="eyebrow">Clinical safety and IG</div><h2>Safety is part of the product architecture.</h2><ul className="list-clean"><li>No autonomous prescribing or medicine stopping</li><li>No silent overwrite of conflicting source states</li><li>Role-based permissions and minimum necessary access</li><li>Full event provenance and immutable audit history</li><li>Defined hazard log, escalation and downtime process</li><li>DPIA, lawful basis, retention and access controls agreed before live data</li></ul></div><div className="card"><span className="badge">Design rule</span><h3 style={{marginTop:12}}>The newest timestamp does not automatically win.</h3><p>If hospital, GP, pharmacy or care-home states disagree, Sitora shows the conflict, the source and the responsible reconciler. The resolved state is the result of accountable reconciliation, not automatic replacement.</p></div></div></section>

    <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Technical acceptance criteria</div><h2>The pilot should not proceed to live intervention unless these are true.</h2></div></div><div className="evidence-triptych"><div className="card"><span className="badge">Data</span><h3>Traceable</h3><p>Every signal can be traced to source data, timestamp and organisation, with known latency and completeness.</p></div><div className="card"><span className="badge">Workflow</span><h3>Owned</h3><p>Every actionable event has a named recipient role, status, escalation route and closure definition.</p></div><div className="card"><span className="badge">Safety</span><h3>Controlled</h3><p>False positives, missed signals and intervention hazards have agreed mitigations and monitoring.</p></div></div></div></section>

    <section className="section pilot-funnel"><div className="shell two-col"><div><div className="eyebrow">Technical discovery output</div><h2>A deployable pilot specification, not a theoretical architecture.</h2><p className="lede">The first four weeks should end with confirmed source systems, field-level data specification, interface method, role model, hazard controls, shadow-mode plan and acceptance tests.</p></div><div className="pilot-funnel-actions"><Link className="button primary" href="/commissioner-summary">Commissioner summary</Link><Link className="button secondary" href="/business-case">Business case</Link></div></div></section>
  </>;
}
