import { dashboardDomains, dashboardPrinciples } from "@/lib/dashboard";

const productOutcomes = [
  ["Medicine Loop","Open medication-change loops","Unresolved cross-setting discrepancies, time-to-reconcile, acknowledgements and confirmed closure."],
  ["WasteGuard","Avoidable supply","Signals reviewed, supplies deferred, dispensing outcome, intervention workload and verified cost avoidance."],
  ["Resource Intelligence","Reusable capacity","Observed pharmacy/nursing time, chair/bed capacity, unused dose change and validated financial effect."],
];

export default function DashboardPage(){return <>
<section className="page-head"><div className="shell"><div className="eyebrow">Measurement dashboard</div><h1>Three products. Three outcome families. No false aggregation.</h1><p className="lede">Sitora keeps medication reconciliation, avoided supply and released capacity separate so a closed loop is not mistaken for a cash saving and a modelled opportunity is not mistaken for verified recovery.</p></div></section>
<section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Product outcomes</div><h2>What a live pilot dashboard would measure.</h2></div></div><div className="evidence-triptych">{productOutcomes.map(([title,headline,body])=><article className="card" key={title}><span className="badge">{title}</span><h3 style={{marginTop:12}}>{headline}</h3><p>{body}</p></article>)}</div></div></section>
<section className="section"><div className="shell metric-grid">{dashboardPrinciples.map(([title,body])=><div className="metric" key={title}><span className="badge">Rule</span><h3>{title}</h3><small>{body}</small></div>)}</div></section>
<section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow">Wider national research</div><h2>Supporting signals remain visible, but outside the product outcome totals.</h2></div><p>Discharge, bed days, appointments and other domains are retained as research evidence and future expansion opportunities.</p></div><div className="opportunity-stack">{dashboardDomains.map(item=><article className="card evidence-card" key={item.id}><div className="meta-row"><span className="badge">{item.domain}</span><span>Confidence: {item.confidence}</span></div><h2>{item.title}</h2><div className="metric-grid"><div className="metric"><span className="badge">Observed</span><strong>{item.observed}</strong><small>{item.observedLabel}</small></div><div className="metric"><span className="badge">Opportunity</span><strong>{item.opportunity}</strong><small>{item.opportunityLabel}</small></div><div className="metric"><span className="badge">Verified</span><strong>{item.verified}</strong><small>{item.verifiedLabel}</small></div></div><details className="reveal-panel"><summary>Interpretation and source</summary><div className="reveal-body"><p>{item.interpretation}</p><a className="source-link" href={item.sourceUrl} target="_blank" rel="noreferrer">Source: {item.sourceLabel} ↗</a></div></details></article>)}</div></div></section>
<section className="section"><div className="shell quote">A closed medication loop, an avoided prescription item and an hour of reusable capacity are all valuable. They are not the same outcome and should never be added together as one savings number.</div></section>
</>}
